### ISSUE TITLE
nsys-ui not working.

### ISSUE THREAD

**Issue by CallumWalley** [nesi/nesi-virtual-desktops#15]
```
module load PyQt/5.12.1-gimkl-2020a-Python-3.8.2
module load Nsight-Systems/2020.5.1
nsys-ui  # this will work only if you have a graphical session

```

**Comment by jennan** [comment]
Hi, thank you @CallumWalley for reporting this issue here.

Some additional context:
- it works with the current version in production server, version 2.3.0 (as reported by pip freeze)
- it doesn't with on test server, version 3.0.6

And here is a screenshot of the reported error from nsys-ui

![image](https://user-images.githubusercontent.com/2003548/169450731-f2a35b54-6db4-4a3e-b0f4-1cf4de968f96.png)

**Comment by CallumWalley** [comment]
Could be something in here https://github.com/nesi/nesi-virtual-desktops/commit/f66b8efe24a948f9fc50f4d80cb0b42b9b3404d5

But more likely something in here: https://github.com/nesi/nesi-virtual-desktops/blob/e376cc9290971f33c02e38763030b7b150637311/util/singularity_wrapper.sh#L54

@jennan

**Comment by jennan** [comment]
@CallumWalley  could it be missing MESA in the base image? f66b8ef removes these
```
yum -y install mesa-libGL 
yum -y install mesa-libGL-devel
yum -y install mesa-libGLU
yum -y install mesa-libGLU-devel
```

**Comment by CallumWalley** [comment]
I think the thought process may have been that they would be included in the base(ist) image, as it may be something we could use on the compute nodes. Either way no harm in adding them to the recipe for rock8vis.def

**Comment by jennan** [comment]
I have tested an image, adding back these packages but this wasn't enough to fix the nsys-ui error :(.

**Comment by jennan** [comment]
so adding back

```
yum -y groupinstall "Xfce"
```

in addition of the mesa packages fixed this issue
